#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## launch waybar with alt config

CONFIG="$HOME/.config/newm/waybar/config"
STYLE="$HOME/.config/newm/waybar/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
