#! /bin/sh

export EDITOR=nvim
export QT_QPA_PLATFORMTHEME="qt5ct"
export $DESKTOP_SESSION="bspwm"

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

fcitx5 &

xinput --set-prop "ELAN1300:00 04F3:3087 Touchpad" "libinput Natural Scrolling Enabled" 1 &
#setxkbmap -option grp:alt_shift_toggle us,es &
xsetroot -cursor_name left_ptr &
#light -S 50 &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
picom -f -b &
$HOME/.config/scripts/thunar.sh &
xss-lock -l $HOME/.config/scripts/lock.sh &
xfce4-power-manager &
blueberry-tray &
nm-applet &
gnome-keyring-daemon --start --components=pkcs11 &

# Pywal theme
#source ~/.cache/wal/colors.sh
#bspc config active_border_color   $background
#bspc config normal_border_color   $background
#bspc config focused_border_color  $background
#bspc config presel_feedback_color $color4

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

# Tokyo-night Theme
bspc config normal_border_color   '#1a1b26'
bspc config active_border_color   '#E0AF68'
bspc config focused_border_color  '#1a1b26'
bspc config presel_feedback_color '#E0AF68'

# Outrun Dark Theme
#bspc config normal_border_color   '#00002a'
#bspc config active_border_color   '#19193f'
#bspc config focused_border_color  '#00002a'
#bspc config presel_feedback_color '#f3r877'

# Solarized Dark Theme
#bspc config normal_border_color   '#002b36'
#bspc config active_border_color   '#073642'
#bspc config focused_border_color  '#002b36'
#bspc config presel_feedback_color '#b58900'

# Onedark Theme
#bspc config normal_border_color   '#282c34'
#bspc config active_border_color   '#3d4148'
#bspc config focused_border_color  '#282c34'
#bspc config presel_feedback_color '#abb2bf'

# Sonokai Andromeda Theme
#bspc config normal_border_color   '#2B2D3A'
#bspc config active_border_color   '#40424d'
#bspc config focused_border_color  '#2B2D3A'
#bspc config presel_feedback_color '#E1E3E4'

bspc config border_width          4
bspc config window_gap            15
bspc config top_padding 		      32
bspc config bottom_padding 		    0
bspc config left_padding 		      0
bspc config right_padding 		    0
bspc config honor_size_hints		  true
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus 		false
bspc config focus_follows_pointer true

bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a mpv state=floating follow=on focus=on
bspc rule -a Galculator state=floating
