#! /bin/sh

# Enviromental variables
export EDITOR=nvim
export QT_QPA_PLATFORMTHEME="qt5ct"
export $DESKTOP_SESSION="bspwm"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SSH_AUTH_SOCK

# Initializers
pgrep -x sxhkd > /dev/null || sxhkd &
xinput --set-prop "ELAN1300:00 04F3:3087 Touchpad" "libinput Natural Scrolling Enabled" 1 &
xsetroot -cursor_name left_ptr &
#redshift &
gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
thunar --daemon &
wmctrl -r Spotify -t 4

# Tray
fcitx5 &
xfce4-power-manager &
blueberry-tray &
nm-applet &

# Bar
$HOME/.config/polybar/launch.sh &
#eww -c $HOME/.config/eww/bar open bar &

# Wallpaper 
nitrogen --restore &

# Compositor
picom -f -b &

# Scripts
$HOME/.config/scripts/thunar.sh &
xss-lock -l $HOME/.config/scripts/lock.sh &
#pkill $HOME/.local/bin/borders ; $HOME/.local/bin/borders &

# bspwm configuration
bspc monitor -d I II III IV V

# Gruvbox Dark Theme
# bspc config normal_border_color   '#282828'
# bspc config active_border_color   '#3c3836'
# bspc config focused_border_color  '#282828'
# bspc config presel_feedback_color '#ebdbb2'

# Nord Theme
# bspc config normal_border_color   '#2e3440'
# bspc config active_border_color   '#2e3440'
# bspc config focused_border_color  '#2e3440'
# bspc config presel_feedback_color '#eceff4'

# Dracula theme
#bspc config normal_border_color   '#282a36'
#bspc config active_border_color   '#282a36'
#bspc config focused_border_color  '#bd93f9'
#bspc config presel_feedback_color '#f8f8f2'

# Tokyo-night Theme
#bspc config normal_border_color   '#1a1b26'
#bspc config active_border_color   '#E0AF68'
#bspc config focused_border_color  '#1a1b26'
#bspc config presel_feedback_color '#E0AF68'

# Outrun Dark Theme
#bspc config normal_border_color   '#00002a'
#bspc config active_border_color   '#19193f'
#bspc config focused_border_color  '#00002a'
#bspc config presel_feedback_color '#f3r877'

# Solarized Dark Theme
#bspc config normal_border_color   '#002b36'
#bspc config active_border_color   '#073642'
#bspc config focused_border_color  '#002b36'
#bspc config presel_feedback_color '#b58900'

# Onedark Theme
#bspc config normal_border_color   '#282c34'
#bspc config active_border_color   '#3d4148'
#bspc config focused_border_color  '#282c34'
#bspc config presel_feedback_color '#abb2bf'

# Sonokai Andromeda Theme
#bspc config normal_border_color   '#2B2D3A'
#bspc config active_border_color   '#40424d'
#bspc config focused_border_color  '#2B2D3A'
#bspc config presel_feedback_color '#E1E3E4'

# Everforest Theme
# bspc config normal_border_color   '#2b3339'
# bspc config active_border_color   '#40474c'
# bspc config focused_border_color  '#2b3339'
# bspc config presel_feedback_color '#d3c6aa'

# Horizon Theme
# bspc config normal_border_color   '#1C1E26'
# bspc config active_border_color   '#32343b'
# bspc config focused_border_color  '#1C1E26'
# bspc config presel_feedback_color '#D2D4DE'

# Catppuccin Theme
bspc config normal_border_color   '#1e1d2f'
bspc config active_border_color   '#1e1d2f'
bspc config focused_border_color  '#1e1d2f'
bspc config presel_feedback_color '#d9e0ee'

# Rose Pine Theme
# bspc config normal_border_color   '#191724'
# bspc config active_border_color   '#191724'
# bspc config focused_border_color  '#c4a7e7'
# bspc config presel_feedback_color '#e0def4'

# Rose Pine Moon Theme
#bspc config normal_border_color   '#232136'
#bspc config active_border_color   '#393552'
#bspc config focused_border_color  '#c4a7e7'
#bspc config presel_feedback_color '#e0def4'

# Rose Pine Dawn Theme
#bspc config normal_border_color   '#f4f4ed'
#bspc config active_border_color   '#f4f4ed'
#bspc config focused_border_color  '#f4f4ed'
#bspc config presel_feedback_color '#f2e9de'

bspc config border_width          4
bspc config window_gap            20
bspc config top_padding           35
bspc config bottom_padding 		    0
bspc config left_padding 		      0
bspc config right_padding 		    0
bspc config honor_size_hints		  true
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config ignore_ewmh_focus 		false
bspc config focus_follows_pointer true

bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a Microsoft-edge desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a Pcmanfm desktop='^3' follow=on
bspc rule -a mpv state=floating follow=on focus=on
bspc rule -a Galculator state=floating

bspc config external_rules_command "$HOME/.config/bspwm/scripts/spotify.sh"
