#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Rosé Pine'
ICONS='Rose-Pine'
FONT='Product Sans 14'
CURSOR='Colloid-dark-cursors'
BTN_LAYOUT=':close'

SCHEMA='gsettings set org.gnome.desktop.interface'
LSCHEMA='gsettings set org.gnome.desktop.wm.preferences'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_layout () {
	${LSCHEMA} button-layout "$BTN_LAYOUT"
}

apply_themes
apply_layout
